-add new version of FindBoost.cmake (from CMake 2.7.20090210),which fixed boost library path issue in Windows -add FindZLIB.cmake -fixed finding SDL library path -change include path for SDL header files -fixed fatal error C1021, because VS don't recognize warning macro